<?php
declare(strict_types=1);
require dirname(__DIR__) . '/rado-system/lib/app.php';
session_name('rado_admin');session_set_cookie_params(['httponly'=>true,'secure'=>!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off','samesite'=>'Strict','path'=>'/']);session_start();if(empty($_SESSION['admin_id'])){http_response_code(403);exit('Forbidden');}
$pdo=rado_db();$type=(string)($_GET['type']??'trips');$allowed=['trips','drivers','settlements','promos','audit'];if(!in_array($type,$allowed,true))$type='trips';$filename='rado-'.$type.'-'.rado_jalali_date(null,false).'.csv';header('Content-Type: text/csv; charset=utf-8');header('Content-Disposition: attachment; filename="'.$filename.'"');echo "\xEF\xBB\xBF";$out=fopen('php://output','wb');
function csvRow($out,array $row):void{fputcsv($out,$row);}
if($type==='trips'){csvRow($out,['شناسه','وضعیت','مسافر','راننده','مبدا','مقصد','کرایه تخمینی','کرایه نهایی','درخواست','پایان']);$q=$pdo->query("SELECT t.*,pu.full_name passenger_name,du.full_name driver_name FROM trips t LEFT JOIN users pu ON pu.id=t.passenger_id LEFT JOIN users du ON du.id=t.driver_id ORDER BY t.requested_at DESC LIMIT 10000");foreach($q->fetchAll() as $r)csvRow($out,[$r['id'],rado_trip_status_fa((string)$r['status']),$r['passenger_name'],$r['driver_name'],$r['pickup_label'],$r['destination_label'],$r['estimated_fare'],$r['final_fare'],rado_jalali_datetime((string)$r['requested_at']),$r['completed_at']?rado_jalali_datetime((string)$r['completed_at']):'']);}
elseif($type==='drivers'){csvRow($out,['شناسه','نام','وضعیت','پلاک','خودرو','کمیسیون','آنلاین','موجودی','آخرین فعالیت']);$q=$pdo->query("SELECT d.*,u.full_name,p.is_online,p.last_seen_at,(SELECT COALESCE(SUM(amount),0) FROM ledger_entries l WHERE l.user_id=d.user_id) balance FROM drivers d JOIN users u ON u.id=d.user_id LEFT JOIN driver_presence p ON p.driver_id=d.user_id ORDER BY u.full_name");foreach($q->fetchAll() as $r)csvRow($out,[$r['user_id'],$r['full_name'],$r['status'],$r['plate_number'],trim((string)$r['vehicle_make'].' '.(string)$r['vehicle_model']),$r['commission_rate'],(int)($r['is_online']??0)?'بله':'خیر',$r['balance'],$r['last_seen_at']?rado_jalali_datetime((string)$r['last_seen_at']):'']);}
elseif($type==='settlements'){csvRow($out,['شناسه','راننده','مبلغ','وضعیت','درخواست','پرداخت']);$q=$pdo->query("SELECT s.*,u.full_name FROM driver_settlements s JOIN users u ON u.id=s.driver_id ORDER BY s.id DESC");foreach($q->fetchAll() as $r)csvRow($out,[$r['id'],$r['full_name'],$r['amount'],$r['status'],rado_jalali_datetime((string)$r['requested_at']),$r['paid_at']?rado_jalali_datetime((string)$r['paid_at']):'']);}
elseif($type==='promos'){csvRow($out,['کد','عنوان','نوع','مقدار','فعال','شروع','پایان']);foreach($pdo->query('SELECT * FROM promo_codes ORDER BY id DESC')->fetchAll() as $r)csvRow($out,[$r['code'],$r['title'],$r['discount_type'],$r['discount_value'],$r['active']?'بله':'خیر',$r['starts_at']?rado_jalali_datetime((string)$r['starts_at']):'',$r['ends_at']?rado_jalali_datetime((string)$r['ends_at']):'']);}
else{csvRow($out,['زمان','نقش','عملیات','نوع','شناسه','IP']);foreach($pdo->query('SELECT * FROM audit_logs ORDER BY id DESC LIMIT 20000')->fetchAll() as $r)csvRow($out,[rado_jalali_datetime((string)$r['created_at']),$r['actor_role'],$r['action'],$r['entity_type'],$r['entity_id'],$r['ip_address']]);}
fclose($out);exit;
