<?php
declare(strict_types=1);
require __DIR__.'/_ui.php';
ra_require_admin();
$pdo=rado_db();$message='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
  ra_require_csrf();
  try{
    $action=(string)($_POST['action']??'');
    if($action==='create_promo'){
      $code=strtoupper(trim((string)($_POST['code']??'')));$title=trim((string)($_POST['title']??''));$type=in_array($_POST['discount_type']??'fixed',['fixed','percent'],true)?(string)$_POST['discount_type']:'fixed';$value=(float)($_POST['discount_value']??0);
      if($code===''||$title===''||$value<=0)throw new RuntimeException('اطلاعات کد تخفیف کامل نیست.');
      $pdo->prepare('INSERT INTO promo_codes(code,title,discount_type,discount_value,max_discount,min_fare,total_limit,per_user_limit,active,starts_at,ends_at) VALUES(?,?,?,?,?,?,?,?,1,?,?)')->execute([$code,$title,$type,$value,($_POST['max_discount']??'')!==''?(int)$_POST['max_discount']:null,(int)($_POST['min_fare']??0),($_POST['total_limit']??'')!==''?(int)$_POST['total_limit']:null,max(1,(int)($_POST['per_user_limit']??1)),($_POST['starts_at']??'')?:null,($_POST['ends_at']??'')?:null]);
      $message='کد تخفیف ساخته شد.';
    }elseif($action==='toggle_promo'){
      $id=(int)($_POST['id']??0);$pdo->prepare('UPDATE promo_codes SET active=1-active WHERE id=?')->execute([$id]);$message='وضعیت کد تخفیف تغییر کرد.';
    }elseif($action==='create_mission'){
      $title=trim((string)($_POST['title']??''));$targetType=in_array($_POST['target_type']??'trips',['trips','online_minutes','revenue'],true)?(string)$_POST['target_type']:'trips';$target=(int)($_POST['target_value']??0);$reward=(int)($_POST['reward_amount']??0);
      if($title===''||$target<=0)throw new RuntimeException('اطلاعات مأموریت کامل نیست.');
      $pdo->prepare('INSERT INTO driver_missions(title,description,target_type,target_value,reward_amount,starts_at,ends_at,active) VALUES(?,?,?,?,?,?,?,1)')->execute([$title,trim((string)($_POST['description']??''))?:null,$targetType,$target,$reward,(string)($_POST['starts_at']??''),(string)($_POST['ends_at']??'')]);$message='مأموریت راننده ساخته شد.';
    }elseif($action==='create_corporate'){
      $title=trim((string)($_POST['title']??''));if($title==='')throw new RuntimeException('نام حساب سازمانی الزامی است.');
      $billing=in_array($_POST['billing_mode']??'prepaid',['prepaid','postpaid'],true)?(string)$_POST['billing_mode']:'prepaid';
      $pdo->prepare('INSERT INTO corporate_accounts(title,contact_phone,billing_mode,credit_limit,balance,active) VALUES(?,?,?,?,?,1)')->execute([$title,trim((string)($_POST['contact_phone']??''))?:null,$billing,(int)($_POST['credit_limit']??0),(int)($_POST['balance']??0)]);$message='حساب سازمانی ساخته شد.';
    }
  }catch(Throwable $e){$error=$e->getMessage();}
}
$promos=ra_table_exists($pdo,'promo_codes')?$pdo->query("SELECT * FROM promo_codes ORDER BY created_at DESC LIMIT 100")->fetchAll():[];
$missions=ra_table_exists($pdo,'driver_missions')?$pdo->query("SELECT * FROM driver_missions ORDER BY starts_at DESC LIMIT 100")->fetchAll():[];
$corporates=ra_table_exists($pdo,'corporate_accounts')?$pdo->query("SELECT * FROM corporate_accounts ORDER BY id DESC LIMIT 100")->fetchAll():[];
$redeemed=ra_table_exists($pdo,'promo_redemptions')?(int)ra_scalar($pdo,"SELECT COUNT(*) FROM promo_redemptions"):0;
$activePromos=ra_table_exists($pdo,'promo_codes')?(int)ra_scalar($pdo,"SELECT COUNT(*) FROM promo_codes WHERE active=1 AND (starts_at IS NULL OR starts_at<=NOW()) AND (ends_at IS NULL OR ends_at>=NOW())"):0;
$activeMissions=ra_table_exists($pdo,'driver_missions')?(int)ra_scalar($pdo,"SELECT COUNT(*) FROM driver_missions WHERE active=1 AND starts_at<=NOW() AND ends_at>=NOW()"):0;
ra_header('رشد و کمپین','growth','تخفیف، مأموریت راننده و حساب سازمانی');
if($message)echo '<div class="notice ok">'.ra_e($message).'</div>';if($error)echo '<div class="notice err">'.ra_e($error).'</div>';
?>
<div class="grid"><div class="card span3 metric"><small>کد تخفیف فعال</small><b><?=$activePromos?></b></div><div class="card span3 metric"><small>استفاده از تخفیف</small><b><?=$redeemed?></b></div><div class="card span3 metric"><small>مأموریت فعال</small><b><?=$activeMissions?></b></div><div class="card span3 metric"><small>حساب سازمانی</small><b><?=count($corporates)?></b></div></div>
<div class="subnav"><a class="on" href="#promo-create">کد تخفیف</a><a href="#mission-create">مأموریت</a><a href="#corporate-create">سازمانی</a></div>
<div class="grid">
 <div class="card span4" id="promo-create"><h2 class="section-title">کد تخفیف جدید</h2><form method="post"><input type="hidden" name="csrf" value="<?=ra_e(ra_csrf())?>"><input type="hidden" name="action" value="create_promo"><div class="formgrid"><div class="field"><label>کد</label><input name="code" required></div><div class="field"><label>عنوان</label><input name="title" required></div><div class="field"><label>نوع</label><select name="discount_type"><option value="fixed">مبلغ ثابت</option><option value="percent">درصد</option></select></div><div class="field"><label>مقدار</label><input name="discount_value" type="number" min="1" required></div><div class="field"><label>حداکثر تخفیف</label><input name="max_discount" type="number" min="0"></div><div class="field"><label>حداقل کرایه</label><input name="min_fare" type="number" min="0" value="0"></div><div class="field"><label>سقف استفاده کل</label><input name="total_limit" type="number" min="1"></div><div class="field"><label>سقف هر کاربر</label><input name="per_user_limit" type="number" min="1" value="1"></div><div class="full"><button class="btn goldbtn">ساخت کد تخفیف</button></div></div></form></div>
 <div class="card span4" id="mission-create"><h2 class="section-title">مأموریت راننده</h2><form method="post"><input type="hidden" name="csrf" value="<?=ra_e(ra_csrf())?>"><input type="hidden" name="action" value="create_mission"><div class="formgrid"><div class="field full"><label>عنوان</label><input name="title" required></div><div class="field"><label>نوع هدف</label><select name="target_type"><option value="trips">تعداد سفر</option><option value="online_minutes">دقیقه آنلاین</option><option value="revenue">درآمد</option></select></div><div class="field"><label>مقدار هدف</label><input name="target_value" type="number" min="1" required></div><div class="field"><label>پاداش (ریال)</label><input name="reward_amount" type="number" min="0" value="0"></div><div class="field"><label>شروع</label><input name="starts_at" type="datetime-local" required></div><div class="field"><label>پایان</label><input name="ends_at" type="datetime-local" required></div><div class="full"><button class="btn goldbtn">ساخت مأموریت</button></div></div></form></div>
 <div class="card span4" id="corporate-create"><h2 class="section-title">حساب سازمانی</h2><form method="post"><input type="hidden" name="csrf" value="<?=ra_e(ra_csrf())?>"><input type="hidden" name="action" value="create_corporate"><div class="formgrid"><div class="field full"><label>نام سازمان</label><input name="title" required></div><div class="field"><label>شماره تماس</label><input name="contact_phone"></div><div class="field"><label>نوع پرداخت</label><select name="billing_mode"><option value="prepaid">پیش‌پرداخت</option><option value="postpaid">پس‌پرداخت</option></select></div><div class="field"><label>سقف اعتبار</label><input name="credit_limit" type="number" min="0" value="0"></div><div class="field"><label>موجودی اولیه</label><input name="balance" type="number" value="0"></div><div class="full"><button class="btn goldbtn">ساخت حساب</button></div></div></form></div>
</div>
<div class="grid"><div class="card span6"><h2 class="section-title">کدهای تخفیف</h2><div class="tablewrap"><table class="table"><tr><th>کد</th><th>عنوان</th><th>نوع</th><th>مقدار</th><th>فعال</th><th>عملیات</th></tr><?php foreach($promos as $p):?><tr><td><b><?=ra_e((string)$p['code'])?></b></td><td><?=ra_e((string)$p['title'])?></td><td><?=ra_e((string)$p['discount_type'])?></td><td><?=ra_e((string)$p['discount_value'])?></td><td><?=$p['active']?'✓':'✕'?></td><td><form method="post"><input type="hidden" name="csrf" value="<?=ra_e(ra_csrf())?>"><input type="hidden" name="action" value="toggle_promo"><input type="hidden" name="id" value="<?=(int)$p['id']?>"><button class="btn"><?=$p['active']?'غیرفعال':'فعال'?></button></form></td></tr><?php endforeach;?></table></div></div><div class="card span6"><h2 class="section-title">مأموریت‌های راننده</h2><div class="tablewrap"><table class="table"><tr><th>عنوان</th><th>هدف</th><th>مقدار</th><th>پاداش</th><th>پایان</th></tr><?php foreach($missions as $m):?><tr><td><?=ra_e((string)$m['title'])?></td><td><?=ra_e((string)$m['target_type'])?></td><td><?=ra_e((string)$m['target_value'])?></td><td><?=ra_money($m['reward_amount'])?></td><td><?=ra_e(ra_date($m['ends_at']))?></td></tr><?php endforeach;?></table></div></div></div>
<div class="card" style="margin-top:14px"><h2 class="section-title">حساب‌های سازمانی</h2><div class="tablewrap"><table class="table"><tr><th>عنوان</th><th>تماس</th><th>مدل صورتحساب</th><th>وضعیت</th></tr><?php foreach($corporates as $c):?><tr><td><?=ra_e((string)$c['title'])?></td><td><?=ra_e((string)($c['contact_phone']??'—'))?></td><td><?=ra_e((string)($c['billing_mode']??'—'))?></td><td><span class="badge"><?=!empty($c['active'])?'فعال':'غیرفعال'?></span></td></tr><?php endforeach;?></table></div></div>
<?php ra_footer();
