<?php
declare(strict_types=1);
require dirname(__DIR__) . '/rado-system/lib/app.php';
$token=trim((string)($_GET['token']??''));
$pdo=rado_db();
$stmt=$pdo->prepare("SELECT s.trip_id,t.status,t.pickup_label,t.destination_label,t.estimated_fare,t.final_fare,t.requested_at,t.accepted_at,t.arrived_at,t.started_at,t.completed_at,u.full_name driver_name,d.plate_number,d.vehicle_make,d.vehicle_model FROM trip_shares s JOIN trips t ON t.id=s.trip_id LEFT JOIN users u ON u.id=t.driver_id LEFT JOIN drivers d ON d.user_id=t.driver_id WHERE s.token=? AND s.revoked_at IS NULL AND s.expires_at>NOW() LIMIT 1");
$stmt->execute([$token]);$r=$stmt->fetch();
if(!is_array($r)){http_response_code(404);?><!doctype html><html lang="fa" dir="rtl"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>RADO</title><style>body{font-family:Tahoma;background:#f5f5f2;display:grid;place-items:center;min-height:100vh;margin:0}.box{background:white;padding:30px;border-radius:26px;max-width:420px}</style><body><div class="box"><h1>RADO</h1><p>لینک سفر معتبر نیست یا منقضی شده است.</p></div></body></html><?php exit;}
$status=rado_trip_status_fa((string)$r['status']);$fare=(int)($r['final_fare']??$r['estimated_fare']??0);$vehicle=trim(((string)($r['vehicle_make']??'')).' '.((string)($r['vehicle_model']??'')));
?><!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>وضعیت سفر RADO</title><meta http-equiv="refresh" content="15"><style>body{margin:0;background:#f5f5f2;color:#171717;font-family:Tahoma,Arial}.wrap{max-width:560px;margin:5vh auto;padding:16px}.card{background:#fff;border-radius:28px;padding:24px;box-shadow:0 16px 50px #0001}.logo{font-size:38px;font-weight:900}.gold{color:#e2a400}.status{margin:18px 0;padding:16px;background:#fff4c8;border-radius:18px;font-weight:900;font-size:20px}.row{padding:12px 0;border-bottom:1px solid #eee}.muted{color:#777;font-size:12px}.fare{font-size:20px;font-weight:900;margin-top:16px}</style></head><body><div class="wrap"><div class="card"><div class="logo">R<span class="gold">A</span>DO</div><div class="muted">اشتراک‌گذاری وضعیت سفر · <?=htmlspecialchars(rado_jalali_datetime(),ENT_QUOTES,'UTF-8')?></div><div class="status"><?=htmlspecialchars($status,ENT_QUOTES,'UTF-8')?></div><div class="row"><b>مبدا</b><br><?=htmlspecialchars((string)$r['pickup_label'],ENT_QUOTES,'UTF-8')?></div><div class="row"><b>مقصد</b><br><?=htmlspecialchars((string)$r['destination_label'],ENT_QUOTES,'UTF-8')?></div><?php if(!empty($r['driver_name'])):?><div class="row"><b>راننده</b><br><?=htmlspecialchars((string)$r['driver_name'],ENT_QUOTES,'UTF-8')?><?php if($vehicle!==''):?> · <?=htmlspecialchars($vehicle,ENT_QUOTES,'UTF-8')?><?php endif;?><?php if(!empty($r['plate_number'])):?> · <?=htmlspecialchars((string)$r['plate_number'],ENT_QUOTES,'UTF-8')?><?php endif;?></div><?php endif;?><div class="fare"><?=number_format($fare)?> ریال</div><p class="muted">این صفحه هر ۱۵ ثانیه خودکار بروزرسانی می‌شود و فقط اطلاعات ضروری سفر را نمایش می‌دهد.</p></div></div></body></html>