name: rado_passenger
description: RADO Passenger - ride hailing app for Baneh
publish_to: none
version: 0.2.0+2

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  geolocator: ^14.0.2
  latlong2: ^0.10.1
  neshan_maps_flutter: ^1.1.0

flutter:
  uses-material-design: true
